In [2]:
import pandas as pd
import numpy as np

In [3]:
rng = np.random.RandomState(42) #42是随机种子
rng # 随机数发生器 random numbers generators

In [4]:
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [5]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), # 把3行4列随机数做成表格（随机，所以不同上）
                  columns=['A','B','C','D'])  # 4列分别是ABCD
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
# If apply a NumPy ufunc on either of these objects, 
# the result is another Pandas object with the indices preserved.
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
# Or, for a slightly more complex calculation
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [8]:
# Example: suppose we are combining two different data sources, 
#  and find only the top three US states by area 
#  and the top three US states by population:

In [9]:
area = pd.Series({'Alaska': 1723337, 
                  'Texas': 695662,
                  'California': 423967}, 
                 name='area')

population = pd.Series({'California': 38332521, 
                        'Texas': 26448193,
                        'New York': 19651127}, 
                       name='population')

In [10]:
# Let's see what happens when we divide these 
#  to compute the population density:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [11]:
# The resulting array contains the union of
#   indices of the two input arrays
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [12]:
# missing number
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [13]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [14]:
A.add(B, fill_value=0) #fill_value关键词

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [15]:
# Index alignment in DataFrame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('IJ')) # 用list分配columns的名字
A

I   J
0  1  11
1  5   1

In [16]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('IJK'))



In [17]:
A + B

I     J   K
0   5.0  11.0 NaN
1  10.0   9.0 NaN
2   NaN   NaN NaN

In [18]:
A

I   J
0  1  11
1  5   1

In [19]:
A.stack()

0  I     1
   J    11
1  I     5
   J     1
dtype: int64

In [20]:
A.stack().mean()

4.5

In [21]:
# Here, fill with the mean of all values in A
#  (computed by first stacking the rows of A):
fill = A.stack().mean()
A.add(B, fill_value=fill)

I     J     K
0   5.0  11.0  13.5
1  10.0   9.0   4.5
2  13.5   6.5  10.5

In [22]:
fill

4.5

In [23]:
#
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [24]:
A[0]

array([3, 8, 2, 4])

In [25]:
A[0].shape

(4,)

In [26]:
A - A[0] # 每一行都减去第一行

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [27]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0] # 每一行都减去第一行

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [28]:
df.iloc[0]

Q    3
R    8
S    2
T    4
Name: 0, dtype: int64

In [29]:
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [30]:
# column-wise
df.subtract(df['R'], axis=0) # 每一列都减去R列

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [36]:
array = ([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
          [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
          [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
          [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
          [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
          [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
          [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
          [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
          [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

df = pd.DataFrame(array,columns=list('ABCDEFGHI'))
df

A   B   C   D   E   F   G   H   I
0  1   2   3   4   5   6   7   8   9
1  2   4   6   8  10  12  14  16  18
2  3   6   9  12  15  18  21  24  27
3  4   8  12  16  20  24  28  32  36
4  5  10  15  20  25  30  35  40  45
5  6  12  18  24  30  36  42  48  54
6  7  14  21  28  35  42  49  56  63
7  8  16  24  32  40  48  56  64  72
8  9  18  27  36  45  54  63  72  81

In [32]:
partofDF = df.iloc[:8, :3] # 指定行列(第8行第3列)以前的所有
partofDF 

A   B   C
0  1   1   3
1  2   4   6
2  3   6   9
3  4   8  12
4  5  10  15
5  6  12  18
6  7  14  21
7  8  16  24

In [33]:
# automatically align
partofDF = df.iloc[::3, ::2] # 行：从0开始，步长为3； 列：从0开始，步长为2
partofDF 

A   C   E   G   I
0  1   3   5   7   9
3  4  12  20  28  36
6  7  21  35  49  63

In [72]:
df

A   B   C   D   E   F   G   H   I
0  1   2   3   4   5   6   7   8   9
1  2   4   6   8  10  12  14  16  18
2  3   6   9  12  15  18  21  24  27
3  4   8  12  16  20  24  28  32  36
4  5  10  15  20  25  30  35  40  45
5  6  12  18  24  30  36  42  48  54
6  7  14  21  28  35  42  49  56  63
7  8  16  24  32  40  48  56  64  72
8  9  18  27  36  45  54  63  72  81

In [73]:
partofDF

A   C   E   G   I
0  1   3   5   7   9
3  4  12  20  28  36
6  7  21  35  49  63

In [74]:
df - partofDF

A   B    C   D    E   F    G   H    I
0  0.0 NaN  0.0 NaN  0.0 NaN  0.0 NaN  0.0
1  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN
2  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN
3  0.0 NaN  0.0 NaN  0.0 NaN  0.0 NaN  0.0
4  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN
5  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN
6  0.0 NaN  0.0 NaN  0.0 NaN  0.0 NaN  0.0
7  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN
8  NaN NaN  NaN NaN  NaN NaN  NaN NaN  NaN

In [75]:
# Missing Data
import numpy as np
import pandas as pd


In [76]:
# None
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [61]:
# dtype = object
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
63.9 ms ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
1.9 ms ± 70.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [74]:
# error
vals1.sum()

In [77]:
# NaN
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [78]:
# like a data virus
1 + np.nan

nan

In [79]:
0 * np.nan

nan

In [80]:
# no errors, but not always useful
vals2.sum(), vals2.min(), vals2.max()

/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


(nan, nan, nan)

In [81]:
# NaN and None
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [88]:
x = pd.Series(range(9), dtype=int)
x

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [89]:
x[0] = None #更改其中一个值
x

0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
dtype: float64

In [77]:
# detecting null values
data = pd.Series([1, np.nan, 'hello', None])

In [78]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [79]:
data.isnull() # NaN 和 None都属于null

0    False
1     True
2    False
3     True
dtype: bool

In [80]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [81]:
data[data.notnull()] # 把notnull的取出来

0        1
2    hello
dtype: object

In [82]:
# remove NA
data.dropna() # 把isnull的扔掉，结果同上

0        1
2    hello
dtype: object

In [83]:
data.fillna("fill")

0        1
1     fill
2    hello
3     fill
dtype: object

In [84]:
# 一个无标题的 DataFrame
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df 

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [85]:
df.dropna() #扔掉有null的行

0    1  2
1  2.0  3.0  5

In [86]:
df.dropna(axis='columns') #扔掉有null的列

2
0  2
1  5
2  6

In [87]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [88]:
df[2] # 指的是index为2的列

0    2
1    5
2    6
Name: 2, dtype: int64

In [89]:
df[3] = np.nan # 加一列index为3，这一列全是nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [90]:
df.dropna(axis='columns', how='all') #扔掉“全空”的列

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [91]:
df.dropna(axis='columns', how ='any') #扔掉“有空”的列

2
0  2
1  5
2  6

In [103]:
df[3] = ([None,1,None])
df

0    1  2    3
0  1.0  NaN  2  NaN
1  2.0  3.0  5  1.0
2  NaN  4.0  6  NaN

In [105]:
df.dropna(how='all') #扔掉“全空”的行

0    1  2    3
0  1.0  NaN  2  NaN
1  2.0  3.0  5  1.0
2  NaN  4.0  6  NaN

In [104]:
df.dropna(how='any') #扔掉“全空”的行

0    1  2    3
1  2.0  3.0  5  1.0

In [93]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [94]:
df.dropna(axis='rows', thresh=3) # 至少有3个数不为nan

0    1  2   3
1  2.0  3.0  5 NaN

In [128]:
# filling null values
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [129]:
data.fillna(0) # 用0fill

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [130]:
# forward-fill
data.fillna(method='ffill') # 空处同上fill

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [131]:
# back-fill
data.fillna(method='bfill') # 空处同下fill

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [132]:
# DataFrame
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [48]:
df.fillna(method='ffill', axis=1) # 空处同左fill

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [134]:
df.fillna(method='bfill', axis=1) #空处同右fill

0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

In [135]:
df1=df.fillna(method='ffill', axis=1)
df1.fillna(method='bfill', axis=1) #先同左后同右fill

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  4.0  4.0  6.0  6.0