In [5]:
import numpy

In [6]:
# check the version
numpy.__version__

'1.15.4'

In [7]:
# import NumPy using np as an alias
import numpy as np

In [8]:
# to display all the contents of the numpy namespace
np.[TAB]

SyntaxError: invalid syntax (<ipython-input-8-24a3f2f1ed32>, line 2)

In [9]:
# to display NumPy's built-in documentation 内建文件 （？）
np?

Type:        module
String form: <module 'numpy' from '/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 

In [10]:
# define three random arrays, a 1-dimensional, 2-dimensional, 
# and 3-dimensional array by NumPy's random number generator. 
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [11]:
# ndim (the number of dimensions)
# shape (the size of each dimension) 
# size (the total size of the array)
print(x3) # 三维数组
print("x3 ndim: ", x3.ndim) # 维度是3
print("x3 shape:", x3.shape) # 各个维度的长度（每个方向上个数） shape = size of each dimension
print("x3 size: ", x3.size) # 各个维度的长度相乘（总个数） total size

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [12]:
# The dtype: the data type of the array
print("dtype:", x3.dtype)

dtype: int64


In [13]:
# The itemsize lists the size (in bytes) of each array element;
# The nbytes lists the total size (in bytes) of the array:

print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [14]:
# In general, nbytes is equal to itemsize times size.

In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[0]

5

In [17]:
# negative indice:
x1[-1]

9

In [18]:
# multi-dimensianl array:using a comma-separated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
x2[0,0]

3

In [20]:
x2[2,0]  #[行，列]

1

In [21]:
x2[2,-1]

7

In [22]:
# Values can also be modified using any of the above index notation:
x2[0, 0] = 12  # 更改其中某一元素
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
x1[0] = 8.159  # this will be truncated!  # 更改其中某一元素，由于这个数组在生成的时候使用了randint，所以此处实数化为整数
x1

array([8, 0, 3, 3, 7, 9])

In [24]:
# One-dimensional subarrays
x = np.arange(10) # 生成从零到n的一维数组
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[:3]  # first five elements

array([0, 1, 2])

In [26]:
x[3:]  # elements after index 5

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [28]:
x[::3]  # 从0开始，步长是3

array([0, 3, 6, 9])

In [29]:
x[1::3]  # 从1开始，步长是3

array([1, 4, 7])

In [30]:
x[::-1]  # reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
x[5::2] # 从5开始，步长是2

array([5, 7, 9])

In [32]:
x[5::-2]  # 从5开始，步长是-2

array([5, 3, 1])

In [33]:
# Multi-dimensional subarrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [34]:
x2[:2, :3]  # 取左上角，2行3列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [35]:
x2[:4, ::2]  # 前4行（此处只有3行，就只取3行），从首列开始、步长为2的列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [36]:
x2[::-1, ::-1]   # 两个维度全部反转

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [37]:
x2[:, 0]  # 第一列

array([12,  7,  1])

In [38]:
x2[0, :]  # 第一行

array([12,  5,  2,  4])

In [39]:
# In the case of row access, the empty slice can be omitted for a more compact syntax:
x2[0]  # equivalent to x2[0, :] 同上

array([12,  5,  2,  4])

In [40]:
# Consider our two-dimensional array from before:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [41]:
# Let's extract a 2x2 subarray from this:
x2_sub = x2[:2, :2] # 取左上角
print(x2_sub)

[[12  5]
 [ 7  6]]


In [42]:
# Now if we modify this subarray, we'll see 
#  that the original array is changed! Observe:
x2_sub[0, 0] = 99 # 替换其中一个数字
print(x2_sub)

[[99  5]
 [ 7  6]]


In [43]:
print(x2) # 上一替换更改了整个母矩阵

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [44]:
# copy()
x2_sub_copy = x2[:2, :2].copy() # 保证母矩阵不会被更改
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [45]:
# If we now modify this subarray, 
#  the original array is not touched:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [46]:
print(x2) # 母矩阵未被更改

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [47]:
aaa = np.arange(1,10) # np.arrange() 生成一个大于等于左，小于右的intArray
print(aaa)

[1 2 3 4 5 6 7 8 9]


In [48]:
bbb = np.arange(10) # np.arrange() 生成一个大于等于左，小于右的intArray
print(bbb)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
grid = aaa.reshape(3,3) # reshape
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
x = np.array([1, 2, 3]) #直接生成矩阵
y = x.reshape(3,1) # reshape括号内有两个数字，reshape成二维

print(x) 
print(y)

[1 2 3]
[[1]
 [2]
 [3]]


In [84]:
# row vector via newaxis -- 在前面加[0]
print(x) # 取数字2: list[1]
print(x[np.newaxis, :]) # 取数字2: list[0][1]

[1 2 3]
[[1 2 3]]


In [75]:
print(y) # 取数字2: list[1][0]
print(y[np.newaxis, :]) # 取数字2: list[0][1][0]

[[1]
 [2]
 [3]]
[[[1]
  [2]
  [3]]]


In [86]:
# column vector via newaxis -- 在后面加[0]
print(x) # 取数字2: list[1]
print(x[:, np.newaxis]) # 取数字2: list[1][0]

[1 2 3]
[[1]
 [2]
 [3]]


In [87]:
print(y) # 取数字2: list[1][0]
print(y[:, np.newaxis]) # 取数字2: list[1][0][0]

[[1]
 [2]
 [3]]
[[[1]]

 [[2]]

 [[3]]]


In [88]:
# concatenating:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [89]:
# concatenate more than two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [104]:
# be used for two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [107]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid, grid, grid], axis=0) # 原维度2*3 改为 8*3（3是第一维的元素个数，axis=0下，3不变）

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [108]:
np.concatenate([grid, grid, grid, grid], axis=1) # 原维度2*3 改为 2*12（2是第二维的元素个数，axis=0下，2不变）

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [109]:
grid.shape

(2, 3)

In [112]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [115]:
# vertically stack the arrays

x = np.array([99, 99, 99])
np.vstack([x, grid])

array([[99, 99, 99],
       [ 9,  8,  7],
       [ 6,  5,  4]])

In [116]:
# horizontally stack the arrays

y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [124]:
# splitting of arrays
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, x4= np.split(x, [3, 5, 7]) # 三个断点，分成四份
print(x1, x2, x3, x4)

[0 1 2] [3 4] [5 6] [7 8 9]


In [125]:
# The related functions np.hsplit and np.vsplit are similar
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
row_012, row_remain = np.vsplit(grid, [3])
print(row_012)
print(row_remain)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [132]:
column_0, column_remain = np.hsplit(grid, [1])
print(column_0)
print(column_remain)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
